import "@fortawesome/fontawesome-free/css/all.min.css";
import "./globals.css";
import Navbar from "./components/ui/Navbar";
import ShuffleButton from "./components/shufflebutton";
export const metadata = {
  title: "Relume",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <div className="card">
          <Navbar />
          {children}
        </div>
      </body>
    </html>
  );
}
